<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="SmokeSuiteMaster" duration-ms="78019" started-at="2018-10-11T18:24:57Z" finished-at="2018-10-11T18:26:15Z">
    <groups>
    </groups>
    <test name="FirefoxTest3" duration-ms="78019" started-at="2018-10-11T18:24:57Z" finished-at="2018-10-11T18:26:15Z">
      <class name="vibe.admin.tests.AdminEcard">
        <test-method status="FAIL" signature="createEcardCategory()[pri:2001, instance:vibe.admin.tests.AdminEcard@2641e737]" name="createEcardCategory" duration-ms="14383" started-at="2018-10-11T23:56:00Z" finished-at="2018-10-11T23:56:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Manage Categories panel is not found under Listing Ecard Templates expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Manage Categories panel is not found under Listing Ecard Templates expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at vibe.ecards.tests.EcardMethods.listOfPanelTitles(EcardMethods.java:186)
	at vibe.ecards.tests.EcardMethods.addEcardCategory(EcardMethods.java:194)
	at vibe.admin.tests.AdminEcard.createEcardCategory(AdminEcard.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:967)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createEcardCategory -->
      </class> <!-- vibe.admin.tests.AdminEcard -->
      <class name="common.DriverInitializerGrid">
        <test-method status="PASS" signature="openBrowser(java.lang.String, java.lang.String)[pri:0, instance:common.DriverInitializerGrid@548ad73b]" name="openBrowser" is-config="true" duration-ms="24576" started-at="2018-10-11T23:54:57Z" finished-at="2018-10-11T23:55:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://monat-stage2.vibeoffice.com/]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
      </class> <!-- common.DriverInitializerGrid -->
      <class name="common.LoginCredentials">
        <test-method status="FAIL" signature="login()[pri:101, instance:common.LoginCredentials@4c762604]" name="login" duration-ms="9641" started-at="2018-10-11T23:55:38Z" finished-at="2018-10-11T23:55:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Signed in successfully.] but found [The user ID or password is incorrect, Please try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Signed in successfully.] but found [The user ID or password is incorrect, Please try again.]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at common.TestBase.confirmationMessage(TestBase.java:988)
	at common.TestBase.logIn(TestBase.java:78)
	at common.LoginCredentials.login(LoginCredentials.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:967)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
      </class> <!-- common.LoginCredentials -->
    </test> <!-- FirefoxTest3 -->
  </suite> <!-- SmokeSuiteMaster -->
</testng-results>
